### ISSUE TITLE
Bitrate and Frame Resolution Configuration?

### ISSUE THREAD

**Issue by ashar02** [zevarito/ErizoClientIOS#10]
In publishing video stream to Licode server, I want to configure video frame resolution, its frame rate and bitrate (fixed value or adaptive). How can it be done from code?
Also regarding publishing audio stream, can I configure audio sampling rate and number of channels too?

**Comment by zevarito** [comment]
I think you are looking for this method: [initWithLocalStreamWithMediaConstraints]
Notice that the object you need to pass as argument is `RTCMediaConstraints` which is part of `libjingle_peerconnection`, that is outside Erizo Client.

Audio IOS API's are changing heavily on Webrtc latest weeks and they haven't concluded their work, so before start going deeper on audio features I'll wait for them to finish what they are doing.

[initWithLocalStreamWithMediaConstraints]:http://zevarito.github.io/ErizoClientIOS/docs/public/html/Classes/ECStream.html#//api/name/initWithLocalStreamWithMediaConstraints:
