### ISSUE TITLE
Information Needed For Ticket # 8

### ISSUE THREAD

**Issue by ashar02** [zevarito/ErizoClientIOS#11]
I mentioned in ticket #8 that if any user leaves from room then video window remains allocated. On further investigation in code, I saw following two room delegates unused. These are:

- (void)room:(ECRoom *)room didUnSubscribeStream:(NSString *)streamId {
    // Clean stuff
}

- (void)room:(ECRoom *)room didRemovedStreamId:(NSString *)streamId {
}

So my question is: if these two delegates are not handled then how video allocated box is reclaimed for other new video stream rendering?

**Comment by zevarito** [comment]
@ashar02 you are being notified when:

1) You have successfully unsubscribed a stream that you choose unsubscribe.
2) A stream in a room you are connected has been removed.

In both cases is up to you to handle resources, free them or do whatever you want.
If you find that un-assign them is not enough or the lib might be leaking memory, please fill a bug for yet or submit a pull request.

Thanks.
