### ISSUE TITLE
mute / un-mute microphone

### ISSUE THREAD

**Issue by vrevidat** [zevarito/ErizoClientIOS#14]
Hi, Any idea how I can mute / un-mute the local microphone?  Thanks!

**Comment by zevarito** [comment]
@vrevidat Hi, ErizoClient doesn't offer an API to do this, you have to look into WebRTC level.

I am planning to add several API calls to handle audio/video once WebRTC team finishes IOS refactor.
I hope in two weeks to have something, keep you posted here.

**Comment by zevarito** [comment]
Fixed: 7dacd4cdfc48e34d764df0fc7527bc1d881a3c8f
