### ISSUE TITLE
how to reconnect to the same peer if it disconnected

### ISSUE THREAD

**Issue by qiangzi611** [zevarito/ErizoClientIOS#15]
I try to reconnect to the same peer if it disconnected.
I use a iphone an a PC browser to test.
1. Both machines are in Video call with each other properly.
2. Disconnect internet either from Local area connection for 3-5 seconds. Reconnect the internet back.
3. Video at both the sides are not able to reconnect.
Did anyone know what can I do?

**Comment by zevarito** [comment]
I think you need to handle this scenario manually.
