### ISSUE TITLE
Erizo Client in C/C++

### ISSUE THREAD

**Issue by ashar02** [zevarito/ErizoClientIOS#18]
Hi @zevarito,
Is there any Erize client code exists, in your knowledge, written in C/C++?? 

Actually, big picture to search such library is to interoperate the SIP and H323 to join room on Licode Sever.

**Comment by zevarito** [comment]
I *think* but not sure, to have read in Licode's issues or discussion list about someone writing a client for C++, perhaps you could check there for something.
