### ISSUE TITLE
Could you please provide a app sample to use ErizoClientOS? 

### ISSUE THREAD

**Issue by wilsonting8fang** [zevarito/ErizoClientIOS#3]
@zevarito 

I am trying to create my app to use ErizoClientOS library, but got some errors.

so it would be great if you can share a sample app with me.

Appreciate your help.

**Comment by wilsonting8fang** [comment]
@zevarito 

I added the following code into my viewController.

RTCEAGLVideoView *localVideoView = [[RTCEAGLVideoView alloc] initWithFrame:CGRectMake(0, 0,
                                                                                          [[UIScreen mainScreen] applicationFrame].size.width,
                                                                                          [[UIScreen mainScreen] applicationFrame].size.height)];
    
    // Add your video view to your UI view
    [self.view addSubview:localVideoView];
    
    // Initialize a local stream
    ECStream *localStream = [[ECStream alloc] initWithLocalStream];
    
    if (localStream.mediaStream.videoTracks.count > 0) {
        RTCVideoTrack *videoTrack = [localStream.mediaStream.videoTracks objectAtIndex:0];
        [videoTrack addRenderer:localVideoView];
    }
However once I run the the project, it returned EXC_BAD_ADDRESS. It was found it was caused by the statement: RTCVideoTrack *videoTrack = [localStream.mediaStream.videoTracks objectAtIndex:0];
And I looked into the code and have not found the root cause so far.

Could you give some comments on it?

**Comment by zevarito** [comment]
@wilsonting8fang did it at least ask you to access camera/mic ?

**Comment by wilsonting8fang** [comment]
@zevarito 

yes, the root cause has been found. I put all the code related to capture camera in viewDidLoad:(

For now it works. but it does make sense if you can share a sample app with me:)

Thanks,

**Comment by wilsonting8fang** [comment]
@zevarito 

yes, the root cause has been found. I created the local variable for video track and stream.

but it still does make sense if you can share a sample app with me.

Thanks.

**Comment by zevarito** [comment]
@wilsonting8fang Unfortunately I have not a sample app in the moment to share, although examples should all be working, please fell free to updates those if you find errors. I will create sample apps to interact with Licode web examples as soon as I get time to it.

**Comment by wilsonting8fang** [comment]
@zevarito 

Thanks for your response. I am looking forward to you're example:)
By the way,  the ticket for "Case 1and case 2" are new issues I found, which are related to get remote audio/video. I am not sure why you closed them:)

**Comment by zevarito** [comment]
Oh sorry for that feel free to re open them, I've closed them cause I think
is something particularly to your env.

On Wednesday, August 26, 2015, wilsonting8fang <notifications@github.com>
wrote:

> @zevarito <https://github.com/zevarito>
>
> Thanks for your response. I am looking forward to you're example:)
> By the way, the ticket for "Case 1and case 2" are new issues I found,
> which are related to get remote audio/video. I am not sure why you closed
> them:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/issues/3#issuecomment-135055762>
> .
>


-- 
Sent from Gmail Mobile
