### ISSUE TITLE
Couldn't subscribe remote stream

### ISSUE THREAD

**Issue by wilsonting8fang** [zevarito/ErizoClientIOS#5]
@zevarito 

Today when I tried to subscribe remote stream as you recommended, however I couldn't get remote stream at all and got the following error log.

- (void)room:(ECRoom *)room didReceiveStreamsList:(NSArray *)list{
    NSLog(@"didReceiveStreamsList");
    
    if ([list count] > 0) {
        // Get the ID of first stream in the list.
        NSDictionary *streamMeta = [list objectAtIndex:0];
        NSLog(@"Stream ID is %@", [streamMeta objectForKey:@"id"]);
        // Subscribe to that stream ID.
       [room subscribe:[streamMeta objectForKey:@"id"]];
    }
}

/*****************************************Log********************************************************/
After that I experienced the error message: 
2015-08-27 23:25:31.527 CodeIOSClient[2335:213932] 
Source: /Users/wenson/ErizoClientIOS/ErizoClient/ECRoom.m:137
💙DEBUG💙: Room: didReceiveRemoteStream

2015-08-27 23:25:33.336 CodeIOSClient[2335:214084] 23:25:33.336 ERROR:     [Thread 0x0x146f6410] AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
2015-08-27 23:25:33.341 CodeIOSClient[2335:213932] didSubscribedStream
2015-08-27 23:25:33.372 CodeIOSClient[2335:213932] 
Source: /Users/wenson/ErizoClientIOS/ErizoClient/ECRoom.m:128

/***************************************End************************************************************/

If I removed the above code to subscribe remote stream, there was no error printed, but I couldn't get remote stream.

Could you take a look at this error? Thanks.

**Comment by wilsonting8fang** [comment]
@zevarito 

And another issue, if iOS device is the first one in the room, the function didReceiveStreamsList will never be called, so looks like there is no way to subscribe the remote stream. 

Thanks,
Wilson

**Comment by wilsonting8fang** [comment]
@zevarito

I think the issue is caused by the following statement.

- (void)room:(ECRoom *)room didSubscribeStream:(ECStream *)stream{
    NSLog(@"didSubscribedStream");
    
    _playerView = [[ECPlayerView alloc] initWithLiveStream:stream];
    // Add your player view to your own view.
    [self.view addSubview:_playerView];
}

However so far I have no idea what is going on here.  Have you experienced the issue?

**Comment by wilsonting8fang** [comment]
@zevarito 

Could you give me some detailed explanation about the work flow in app based on ErizoClientIOS.
Here I am copying my env and the work flow for your reference.

I am using iPhone (iOS 8.4.1) and in my controlerView:

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
   
    _localVideoView = [[RTCEAGLVideoView alloc] initWithFrame:CGRectMake(20, 40, [[UIScreen mainScreen] applicationFrame].size.width/2-20,
                                                                          [[UIScreen mainScreen] applicationFrame].size.height/3) ];
                       
    
    
    // Add your video view to your UI view
    [self.view addSubview:_localVideoView];
    
    _localStream = [[ECStream alloc] initWithLocalStream];
    
    if (_localStream.mediaStream.videoTracks.count > 0) {
        _localVideoTrack = [_localStream.mediaStream.videoTracks objectAtIndex:0];
        [_localVideoTrack addRenderer:_localVideoView];
    }
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        _room = [[ECRoom alloc] initWithEncodedToken:tokenStr delegate:self];
        dispatch_async(dispatch_get_main_queue(), ^{
            
        });
    });
 
}

- (void)room:(ECRoom *)room didGetReady:(ECClient *)client{
    NSLog(@"didGetReady");
    [_room publish:_localStream withOptions:@{@"data": @FALSE}];
    
}


- (void)room:(ECRoom *)room didSubscribeStream:(ECStream *)stream{
    NSLog(@"didSubscribedStream");
    
    _playerView = [[ECPlayerView alloc] initWithLiveStream:stream];
    //NSLog(@"get remote stream Id %@", stream.streamId);
    // Add your player view to your own view.
    [self.view addSubview:_playerView];
}

- (void)room:(ECRoom *)room didReceiveStreamsList:(NSArray *)list{
    NSLog(@"didReceiveStreamsList");
    
    if ([list count] > 0) {
        // Get the ID of first stream in the list.
        NSDictionary *streamMeta = [list objectAtIndex:0];
        NSLog(@"Remote Stream ID is %@", [streamMeta objectForKey:@"id"]);
        // Subscribe to that stream ID.
        
        _remoteStreamId = [streamMeta objectForKey:@"id"];
      [room subscribe:[streamMeta objectForKey:@"id"]];
    }
    
}


but I always experienced AVAudioSession issue:
2015-08-28 22:48:05.029 CodeIOSClient[2546:244093] 22:48:05.028 ERROR:     [Thread 0x0x16ef7040] AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

Could you please check whether there is something wrong in my flow? 

Thanks,
Wilson

**Comment by zevarito** [comment]
@wilsonting8fang I am setting up an example app.

**Comment by wilsonting8fang** [comment]
@zevarito  Looks like Licode couldn't use the latest node.js, which should be installed when installing licode.

And licode is using node.js with version V.0.10.37.
Hope it helps.

**Comment by zevarito** [comment]
I mean examples seem to not working, I cannot get a valid token from there.

2015-08-29 1:06 GMT-03:00 wilsonting8fang <notifications@github.com>:

> @zevarito <https://github.com/zevarito> Looks like Licode couldn't use
> the latest node.js, which should be installed when installing licode.
>
> And licode is using node.js with version V.0.10.37.
> Hope it helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/issues/5#issuecomment-135938253>
> .
>



-- 
Alvaro

**Comment by wilsonting8fang** [comment]
@zevarito 

I am copying my test code for your reference, which has been tested. I think you should replace the ip address and room number.

- (void)createToken{
    NSString *roomTokenCmd = @"http://192.168.199.8:3001/createToken/";
    NSURL * roomURL = [NSURL URLWithString:roomTokenCmd];
    NSMutableURLRequest * request = [NSMutableURLRequest requestWithURL:roomURL];
    NSDictionary * json = @{
                            @"username":@"user",
                            @"role": @"presenter",
                            @"room": @"55d869e82ff063e152d8ea7f"
                            //@"room":@"55dcb507d965910b26d60832"
                            };
    NSData * data = [NSJSONSerialization dataWithJSONObject:json options:NSJSONWritingPrettyPrinted error:nil];
    
    request.HTTPMethod = @"POST";
    request.HTTPBody = data;
    [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    [NSURLConnection sendAsynchronousRequest:request
                                              queue:[NSOperationQueue mainQueue]
                                                     completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
                                                         
                                                         NSString * tokenStr = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
                                                         NSLog(@"Token: %@",tokenStr);
                                                         NSData *decodedData = [[NSData alloc] initWithBase64EncodedString:tokenStr options:0];
                                                         NSError *jsonParseError = nil;
                                                         NSDictionary * decodedToken = [NSJSONSerialization
                                                                                        JSONObjectWithData:decodedData
                                                                                        options:0
                                                                                        error:&jsonParseError];
                                                         NSString * host = [decodedToken objectForKey:@"host"];
                                                         BOOL  secure = (BOOL)[decodedToken objectForKey:@"secure"];
                                                         NSLog(@"Secure %@", secure?@"True":@"False");
                                                         NSLog(@"Host: %@", host);
                                                         
                                                         _room = [[ECRoom alloc] initWithEncodedToken:tokenStr delegate:self];
                                                     }];

**Comment by zevarito** [comment]
Thanks @wilsonting8fang, I wished to connect with Licode examples so the IOS example shows the interoperability between devices.

**Comment by zevarito** [comment]
@wilsonting8fang I've created an example app, so far it connects to a Room and Publish your local stream. Check it out in ECIExample project after open ErizoClientIOS workspace.

You will need to follow instructions on README about how to get it working to get an access token.

**Comment by wilsonting8fang** [comment]
@zevarito 

Actually I got the publish my local stream successfully, and the problem I experienced was related to subscribe the remote stream after publishing my local stream.

Could you have a try to subscribe the remote stream after publishing your local stream?

**Comment by zevarito** [comment]
Hehe, well I'll write it by monday 😊

Would be great if you can pull request the consumer example part even if it
is not working for you so I can see how you are doing it.

xconfig and plist should have same configuration settings to get a consumer
access token.

On Saturday, August 29, 2015, wilsonting8fang <notifications@github.com>
wrote:

> @zevarito <https://github.com/zevarito>
>
> Actually I got the publish my local stream successfully, and the problem I
> experienced was related to subscribe the remote stream after publishing my
> local stream.
>
> Could you have a try to subscribe the remote stream after publishing your
> local stream?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/issues/5#issuecomment-135997290>
> .
>


-- 
Sent from Gmail Mobile

**Comment by zevarito** [comment]
I've added a consumer example as well.

**Comment by wilsonting8fang** [comment]
@zevarito 

Thanks for example. However the issue still exists:(  After subscribing remote stream, I can't here the voice from both sides. And got the following error. 
AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
2015-09-01 14:37:20.664 ECIExample[4086:442043] 

By the way I am using IOS8.4.1 for test. I am not sure if it is related to IOS version.
