### ISSUE TITLE
Room joining issue

### ISSUE THREAD

**Issue by ashar02** [zevarito/ErizoClientIOS#8]
I am using this code (ECIExampleLicode) to join room in Licode server. This app works well, if I join as first user. But if I join room where one or two users are already present, it shows black boxes against that user(s). If some one leaves room then that user's box does not disappear from the list. Also if app goes into background and then comes to foreground it crashes.

**Comment by zevarito** [comment]
Afaik that should not be happening, see the example screenshot on the
README, it looks like the same scenario you are mentioning and it worked
fine for me, getting first into the room, or second, or third. I've been
using an Iphone 5s with IOS 8.x.

I will check once again to see if something changed

That is happening with the latest codebase?

That is connecting to Licode's server or your own server?

Which device are you using for the tests?

There is any relevant Debug/Error/Warning message in the console?

You right, I didn't worked yet on the fore/back modes, please share the
error you get there.

2015-09-14 9:54 GMT-03:00 ashar02 <notifications@github.com>:

> I am using this code (ECIExampleLicode) to join room in Licode server.
> This app works well, if I join as first user. But if I join room where one
> or two users are already present, it shows black boxes against that
> user(s). Also if app goes into background and then comes to foreground it
> crashes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/issues/8>.
>



-- 
Alvaro

**Comment by ashar02** [comment]
![screen shot 2015-09-14 at 7 37 40 pm](https://cloud.githubusercontent.com/assets/1763187/9852529/3c77f39e-5b18-11e5-98d7-239fd6eb39ff.png)
I am using device iPad mini. iOS version is 7.1.2.
And yes we are using our own deployment of Licode. We took the code of Licode in last year November.

**Comment by zevarito** [comment]
@ashar02 There seems to be issues when compiling against arm64, looking into that, help is welcome.

**Comment by zevarito** [comment]
@ashar02 I will rename this issue as `handle foreground/background modes` and please refer to this one: https://github.com/zevarito/ErizoClientIOS/issues/7 for arm64 issues which I think you are experiencing with your ipad mini when are not being able to join a room. Thanks.

**Comment by zevarito** [comment]
Actually I will close if favor of #9
